### PR TITLE
changed credential file existence check with spn values check

### PR DESCRIPTION
**Pull request by gianlucaciocci**
This pull request covers the issue titled "env variables azure_backend.rb library issue, if credential file not present".

Signed-off-by: Gianluca Ciocci gianluca.ciocci@contino.io

### CODE REVIEW

**Comment by gianlucaciocci** [comment]
I am not understanding why TravisCi checks are failing...anyone can help? What am I missing? I haven't a Travis CI for private projects account...does that have an impact on those checks?

**Comment by chris-rock** [comment]
@gianlucaciocci Thank you very much for the PR. You and @russellseymour did a great job covering the additional check. We opted for #42 since it was already green. Please let me know if you agree with that decision or if you think we missed something.

**Comment by gianlucaciocci** [comment]
Hi @chris-rock, thanks a lot for this message and for taking @russellseymour merge. I was actually looking forward to this fix. So no problem at all. 
On another note, what's your plan about inspec for Azure. We are "using it in anger" on a project I am on...

**Comment by chris-rock** [comment]
@gianlucaciocci We are currently working on InSpec 2.0 https://github.com/chef/inspec/milestone/26 which includes to implement the RFC Platforms https://github.com/chef/inspec/issues/1661. Once this is in, we are going to merge this repo into core inspec. Not sure what you mean by "using it in anger"? Can you explain this more?

**Pull request closed without merging**
